apiVersion: v1
kind: Service
metadata:
  name: android-emulator
  namespace: android-emulator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: android-emulator
  ports:
    - name: appium
      port: 4723
      targetPort: appium
